Update remote monitoring in Provider Portal to use preview 2
Microsoft/healthvault-samples pull request #17
Opened 2017-06-09 22:02 UTC by LiquidPT

Preview 2 enhances the task API schedules. Added support to the PRovider Portal for this. Also minor Goals updates

2017-06-09 22:02 UTC, msftclas commented
@LiquidPT,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-13 22:19 UTC, gcorvera commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Guid personId, Guid recordId)
>? [](start = 49, length = 1)

Show we have two different controllers depending on if the id is provided or not? This logic is kind of weird to follow. Consider having:
public async Task<ActionResult> Goal(Guid id, Guid personId, Guid recordId) and public async Task<ActionResult> Goal(Guid personId, Guid recordId) and separate the two methods.

2017-06-13 22:23 UTC, gcorvera commented
:shipit:

2017-06-14 17:39 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Guid personId, Guid recordId)
Interesting. I'll try that out. It'll end up loading the same view either way.

2017-06-14 17:48 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Guid personId, Guid recordId)
If I do that, the router finds the action methods ambiguous. One of these would have to be named something else.

2017-06-14 19:44 UTC, miburf commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +            if (id.HasValue)
&& id.Value != Guid.Empty like below?

2017-06-14 19:44 UTC, miburf commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public ActionResult GoalRecommendation(Guid personId, Guid recordId)
personId & recordId not used?

2017-06-14 19:59 UTC, kevineger requested changes
Mostly nits but a few questions seeking clarification/changes.

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Content/Site.css
> +.btn-link {
Feel like specific styling on buttons is not needed for a sample app.

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Goal goal, Guid personId, Guid recordId)
Why can post take in an id?

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Goal goal, Guid personId, Guid recordId)
A POST shouldn't optionally update.

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +            if (recommendation?.AssociatedGoal?.RecurrenceMetrics?.OccurrenceCount == null && recommendation?.AssociatedGoal?.RecurrenceMetrics?.WindowType == GoalRecurrenceType.Unknown.ToString())
Can you remove the conditional access on the second expression of the &&? They already get evaluated in the first expression.

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        [HttpPost]
Delete is a POST?

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Helpers/Builder.cs
> +            plan.AssociatedTasks = new Collection<ActionPlanTaskV2> { task };
Nit: Use object initializer on plan as you do objective.

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Views/ActionPlan/TrackingValidationEntry.cshtml
> -            <div class="col-md-12 slim-col"">
lol

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Views/Goals/GoalRecommendation.cshtml
> +                <input type="submit" value="Save" class="btn btn-default" />
I think the other save buttons are btn-success styled. If not, maybe they should be?

2017-06-14 19:59 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Views/Goals/Index.cshtml
> +                    @Html.ActionLink("Edit", "Goal", new { id = goal.Id, personId = Request.Params["personId"], recordId = Request.Params["recordID"] })
Nit: `"personId"` vs `"recordID"` - inconsistent casing.

2017-06-14 20:16 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Goal goal, Guid personId, Guid recordId)
This is a form post in a website. the same page is used for create and update, depending on whether there's an ID

2017-06-14 20:18 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Views/Goals/GoalRecommendation.cshtml
> +                <input type="submit" value="Save" class="btn btn-default" />
This was copied form the goal page. Looking at other pages, the save are btn-default

2017-06-14 20:19 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Content/Site.css
> +.btn-link {
This was needed to get a button that's styled like a link to line up with other links

2017-06-14 20:24 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +            if (recommendation?.AssociatedGoal?.RecurrenceMetrics?.OccurrenceCount == null && recommendation?.AssociatedGoal?.RecurrenceMetrics?.WindowType == GoalRecurrenceType.Unknown.ToString())
Maybe. I don't think it hurts to be redundant in this case in case bits are copy/pasted

2017-06-14 20:39 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +            if (recommendation?.AssociatedGoal?.RecurrenceMetrics?.OccurrenceCount == null && recommendation?.AssociatedGoal?.RecurrenceMetrics?.WindowType == GoalRecurrenceType.Unknown.ToString())
It will still work as intended, just more optimized to remove.

2017-06-14 20:45 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Goal goal, Guid personId, Guid recordId)
Forms can take on different http verbs as methods. I personally would not have Create, Update and Delete all being `[HttpPost]`.

2017-06-14 20:49 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +            if (id.HasValue)
fixed

2017-06-14 20:50 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public ActionResult GoalRecommendation(Guid personId, Guid recordId)
fixed

2017-06-14 20:51 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Goal goal, Guid personId, Guid recordId)
See this [relevent SO answer](https://stackoverflow.com/a/17663249)

2017-06-14 20:56 UTC, kevineger commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Guid personId, Guid recordId)
Specifying the corresponding attribute should resolve the ambiguity, ie: `[HttpGet]`, `[HttpPost]`, etc.

2017-06-14 21:07 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Goal goal, Guid personId, Guid recordId)
Filed a bug to look at this later

2017-06-14 21:07 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        [HttpPost]
Filed a bug to look at this later

2017-06-14 21:21 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Views/Goals/Index.cshtml
> +                    @Html.ActionLink("Edit", "Goal", new { id = goal.Id, personId = Request.Params["personId"], recordId = Request.Params["recordID"] })
fixed

2017-06-14 21:21 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Helpers/Builder.cs
> +            plan.AssociatedTasks = new Collection<ActionPlanTaskV2> { task };
fixed

2017-06-15 17:28 UTC, LiquidPT commented on dotNETStandard/HealthVaultProviderManagementPortal/HealthVaultProviderManagementPortal/Controllers/GoalsController.cs
> +        public async Task<ActionResult> Goal(Guid? id, Guid personId, Guid recordId)
It's a get. They're both gets.

2017-06-16 01:16 UTC, merged